-- V1: initial schema, mirrors the JPA entities in com.example.project.model.
-- Uses IF NOT EXISTS so it is safe on databases previously created by hibernate ddl-auto=update.

CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone    VARCHAR(255),
    address  VARCHAR(255),
    role     VARCHAR(255),
    enabled  BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS seller_profiles (
    sellprofile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL,
    bankaccount    VARCHAR(255) NOT NULL,
    rating         NUMERIC(3, 2),
    salecount      INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_seller_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_seller_profiles_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS artworks (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR(255) NOT NULL,
    image_url VARCHAR(2048),
    seller_id BIGINT,
    CONSTRAINT fk_artworks_seller FOREIGN KEY (seller_id) REFERENCES seller_profiles (sellprofile_id)
);

CREATE TABLE IF NOT EXISTS biddings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_bid        NUMERIC(19, 4),
    user_id         BIGINT,
    winner_user_id  BIGINT,
    seller_rating   INTEGER,
    starting_price  NUMERIC(19, 4),
    start_date      TIMESTAMP(6),
    end_date        TIMESTAMP(6),
    status          VARCHAR(255) NOT NULL,
    CONSTRAINT fk_biddings_owner  FOREIGN KEY (user_id)        REFERENCES users (id),
    CONSTRAINT fk_biddings_winner FOREIGN KEY (winner_user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS bidding_artworks (
    bidding_id BIGINT NOT NULL,
    artwork_id BIGINT NOT NULL,
    PRIMARY KEY (bidding_id, artwork_id),
    CONSTRAINT fk_bidding_artworks_bidding FOREIGN KEY (bidding_id) REFERENCES biddings (id),
    CONSTRAINT fk_bidding_artworks_artwork FOREIGN KEY (artwork_id) REFERENCES artworks (id)
);

CREATE TABLE IF NOT EXISTS bidactions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount            NUMERIC(19, 4) NOT NULL,
    user_id           BIGINT,
    bidding_id        BIGINT,
    timestamp         TIMESTAMP(6),
    status            VARCHAR(255) NOT NULL,
    voided_at         TIMESTAMP(6),
    voided_by_user_id BIGINT,
    void_reason       VARCHAR(500),
    CONSTRAINT fk_bidactions_user       FOREIGN KEY (user_id)           REFERENCES users (id),
    CONSTRAINT fk_bidactions_bidding    FOREIGN KEY (bidding_id)        REFERENCES biddings (id),
    CONSTRAINT fk_bidactions_voided_by  FOREIGN KEY (voided_by_user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message    VARCHAR(2000) NOT NULL,
    thumbsup   INTEGER NOT NULL DEFAULT 0,
    thumbsdown INTEGER NOT NULL DEFAULT 0,
    user_id    BIGINT,
    bidding_id BIGINT NOT NULL,
    CONSTRAINT fk_comments_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_comments_bidding FOREIGN KEY (bidding_id) REFERENCES biddings (id)
);

CREATE TABLE IF NOT EXISTS comment_reactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    type       VARCHAR(20) NOT NULL,
    CONSTRAINT uk_comment_reactions_comment_user UNIQUE (comment_id, user_id),
    CONSTRAINT fk_comment_reactions_comment FOREIGN KEY (comment_id) REFERENCES comments (id),
    CONSTRAINT fk_comment_reactions_user    FOREIGN KEY (user_id)    REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS payments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bidding_id        BIGINT NOT NULL,
    buyer_user_id     BIGINT NOT NULL,
    seller_profile_id BIGINT NOT NULL,
    amount            NUMERIC(19, 4) NOT NULL,
    status            VARCHAR(30) NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL,
    due_date          TIMESTAMP(6) NOT NULL,
    slip_url          VARCHAR(2048),
    paid_at           TIMESTAMP(6),
    confirmed_at      TIMESTAMP(6),
    reject_reason     VARCHAR(500),
    shipping_address  VARCHAR(1000),
    carrier           VARCHAR(100),
    tracking_number   VARCHAR(100),
    tracking_url      VARCHAR(2048),
    shipping_note     VARCHAR(1000),
    shipped_at        TIMESTAMP(6),
    completed_at      TIMESTAMP(6),
    cancelled_at      TIMESTAMP(6),
    cancel_reason     VARCHAR(500),
    CONSTRAINT uk_payments_bidding UNIQUE (bidding_id),
    CONSTRAINT fk_payments_bidding FOREIGN KEY (bidding_id)        REFERENCES biddings (id),
    CONSTRAINT fk_payments_buyer   FOREIGN KEY (buyer_user_id)     REFERENCES users (id),
    CONSTRAINT fk_payments_seller  FOREIGN KEY (seller_profile_id) REFERENCES seller_profiles (sellprofile_id)
);

-- Indexes on foreign keys / frequently filtered columns
CREATE INDEX IF NOT EXISTS idx_artworks_seller        ON artworks (seller_id);
CREATE INDEX IF NOT EXISTS idx_biddings_status_end    ON biddings (status, end_date);
CREATE INDEX IF NOT EXISTS idx_biddings_owner         ON biddings (user_id);
CREATE INDEX IF NOT EXISTS idx_biddings_winner        ON biddings (winner_user_id);
CREATE INDEX IF NOT EXISTS idx_bidactions_bidding     ON bidactions (bidding_id);
CREATE INDEX IF NOT EXISTS idx_bidactions_user        ON bidactions (user_id);
CREATE INDEX IF NOT EXISTS idx_comments_bidding       ON comments (bidding_id);
CREATE INDEX IF NOT EXISTS idx_comments_user          ON comments (user_id);
CREATE INDEX IF NOT EXISTS idx_payments_buyer         ON payments (buyer_user_id);
CREATE INDEX IF NOT EXISTS idx_payments_seller        ON payments (seller_profile_id);
CREATE INDEX IF NOT EXISTS idx_payments_status_due    ON payments (status, due_date);
