spring.application.name=project

# Database ค่าหลัง : คือค่า default สำหรับเครื่อง dev ตอน deploy จะส่งผ่าน environment variable
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/auction}
spring.datasource.username=${DB_USERNAME:auction}
spring.datasource.password=${DB_PASSWORD:auction}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
